Challenge detail UI
DriveQuantPublic/drivekit-ui-android pull request #100
Opened 2021-06-01 07:59 UTC by mohamed-garci

2021-06-04 13:25 UTC, Steven-DriveQuant commented
@mohamed-garci Peux-tu résoudre le conflit sur les deux fichiers ?

2021-06-04 13:30 UTC, Steven-DriveQuant commented on ChallengeUI/src/main/res/layout/dk_fragment_challenge_ranking.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Ce `<LinearLayout>` est peut-être inutile. Voir si on peut le remplacer par un `<merge>` afin d'avoir un niveau de moins

2021-06-04 14:17 UTC, Steven-DriveQuant requested changes

2021-06-04 14:17 UTC, Steven-DriveQuant commented on ChallengeUI/src/main/java/com/drivequant/drivekit/challenge/ui/challengedetail/fragment/ChallengeResultsFragment.kt
> +                it.tintDrawable(Color.parseColor("#FFD232"))
Ce code hexa correspond à `dkRatingBarForegroundColor`. Faut-il l'écrire ici en dur ou bien appeler directement `dkRatingBarForegroundColor` ?

2021-06-04 14:17 UTC, Steven-DriveQuant commented on ChallengeUI/src/main/java/com/drivequant/drivekit/challenge/ui/challengedetail/fragment/ChallengeRulesFragment.kt
> +        DriveKitUI.analyticsListener?.trackScreen(
Pour ce fragment (et les 3 autres Ranking, Results et Trips, on passe dans `onActivityCreated()` et donc on appelle `trackScreen()` alors que l'utilisateur n'a pas encore affiché le fragment Rules.

Ainsi, on considère que l'utilisateur a affiché l'écran Rules alors qu'il vient seulement d'ouvrir l'écran de détail d'un challenge

2021-06-04 14:17 UTC, Steven-DriveQuant commented on ChallengeUI/src/main/java/com/drivequant/drivekit/challenge/ui/common/ChallengeTripExtension.kt
> +fun Trip.toDKTripItem() = object: DKTripListItem {
Passer en `internal` si possible

2021-06-04 14:17 UTC, Steven-DriveQuant commented on ChallengeUI/src/main/java/com/drivequant/drivekit/challenge/ui/common/ChallengeTripExtension.kt
> +fun List<Trip>.toDKTripList(): List<DKTripListItem> {
Passer en internal ici aussi si possible. La méthode peut d'ailleurs être simplifiée de la façon suivante :

```fun List<Trip>.toDKTripList(): List<DKTripListItem> = this.map { it.toDKTripItem()}```

2021-06-04 14:19 UTC, Steven-DriveQuant commented
J'ai également vu que l'utilisateur n'accédait ni à la liste des challenges, ni au détail d'un challenge lorsque des données étaient déjà présentes en base locale et que l'utilisateur n'a pas de connexion. Il faudrait gérer ce cas car c'est actuellement le cas sur l'app de production

2021-06-07 07:22 UTC, mohamed-garci commented on ChallengeUI/src/main/res/layout/dk_fragment_challenge_results.xml
> +        <LinearLayout
ça été modifié, merci !

2021-06-07 07:23 UTC, mohamed-garci commented on ChallengeUI/src/main/res/layout/dk_fragment_challenge_results.xml
> +                                tools:ignore="NewApi" />
ça été retiré

2021-06-07 07:23 UTC, mohamed-garci commented on ChallengeUI/src/main/java/com/drivequant/drivekit/challenge/ui/challengedetail/activity/ChallengeDetailActivity.kt
> +        const val CHALLENGE_ID_EXTRA = "challenge-id-extra"
Done

2021-06-07 07:26 UTC, mohamed-garci commented on ChallengeUI/src/main/java/com/drivequant/drivekit/challenge/ui/challengedetail/fragment/ChallengeRulesFragment.kt
> +        DriveKitUI.analyticsListener?.trackScreen(
J'ai déplacé le code dans le méthode `onViewCreated()`

2021-06-07 07:28 UTC, mohamed-garci commented
> J'ai également vu que l'utilisateur n'accédait ni à la liste des challenges, ni au détail d'un challenge lorsque des données étaient déjà présentes en base locale et que l'utilisateur n'a pas de connexion. Il faudrait gérer ce cas car c'est actuellement le cas sur l'app de production

L'accès offline à la liste + détail est désormais fonctionnel, bien vu

2021-06-07 14:20 UTC, Steven-DriveQuant approved these changes

2021-06-07 14:32 UTC, merged