Vehicle UI : Optimize vehicles synchronization
DriveQuantPublic/drivekit-ui-android pull request #142
Opened 2021-11-22 11:27 UTC by mohamed-garci

2021-11-22 15:04 UTC, mohamed-garci commented
Test à faire : 

- Afficher la liste des véhicules pour la première fois (base de données local vide) => loader + écran blanc
- Afficher la liste des véhicules une deuxième fois => la liste récupère et affiche les véhicules de la base local, ensuite synchronisation ce lance (Loader qui s'affiche)
- Ajouter un nouveau véhicule => la liste doit contenir ce nouveau véhicule créé
- Supprimer un véhicule => l'item doit être retiré de la liste
- Ajoute un véhicule sur un autre device => pull to refresh sur la liste (le véhicule ajouté doit présent sur la liste)

2021-11-22 16:31 UTC, Steven-DriveQuant requested changes

2021-11-22 16:31 UTC, Steven-DriveQuant commented on VehicleUI/src/main/java/com/drivequant/drivekit/vehicle/ui/vehicles/fragment/VehiclesListFragment.kt
> +        updateVehicles(synchronizationType)
Il serait préférable d'implémenter le même mécanisme que sur la liste des challenges. Cette solution fonctionne mais va rencontrer dans le cas suivant :
- L'utilisateur n'a pas de véhicules synchronisés en local
- Un appel au service de synchro véhicules est fait avant d'accéder à la liste des véhicules
- Avant que cet appel soit fini, l'utilisateur accède à la liste des véhicules 
Dans ce schéma là, l'utilisateur ne devrait pas avoir de callback. Peux-tu vérifier ce use-case ? Merci !

2021-11-24 14:29 UTC, mohamed-garci commented on VehicleUI/src/main/java/com/drivequant/drivekit/vehicle/ui/vehicles/fragment/VehiclesListFragment.kt
> +        updateVehicles(synchronizationType)
Finalement le cas a été géré.

2021-11-24 16:08 UTC, merged