Release/1.38
DriveQuantPublic/drivekit-ui-android pull request #320
Opened 2023-07-12 07:12 UTC by DavidBauduin

2023-07-12 16:02 UTC, Steven-DriveQuant requested changes

2023-07-13 06:08 UTC, DavidBauduin commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/driverprofile/DriverProfileViewModel.kt
> +                        DKPeriod.YEAR -> Date().startingFrom(CalendarField.YEAR)
J'ai modifié

2023-07-13 06:09 UTC, DavidBauduin commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/driverprofile/component/profilefeature/DriverProfileFeatureViewModel.kt
> +    class ParametrizedDescription(@StringRes val descriptionId: Int, vararg param: String) :
Ah oui bien vu ! Merci, c'est corrigé

2023-07-13 06:09 UTC, DavidBauduin commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/mysynthesis/MySynthesisFragment.kt
> +        this.buttonDetail.visibility = View.GONE
Dans les specs il est prévu un bouton "Comment m'améliorer ?". C'est mieux de garder du coup non ?

2023-07-17 14:03 UTC, merged