Feature/android 11 migration
DriveQuantPublic/drivekit-ui-android pull request #45
Opened 2020-08-27 09:47 UTC by mohamed-garci

2020-08-27 12:38 UTC, Steven-DriveQuant requested changes

2020-08-27 12:38 UTC, Steven-DriveQuant commented on PermissionsUtilsUI/src/main/java/com/drivequant/drivekit/permissionsutils/permissions/activity/LocationPermissionActivity.kt
> +                getString(R.string.dk_perm_utils_permissions_location_text1_android11)
Passer par DKResource.convertToString()

2020-08-27 12:38 UTC, Steven-DriveQuant commented on PermissionsUtilsUI/src/main/java/com/drivequant/drivekit/permissionsutils/permissions/activity/LocationPermissionActivity.kt
> +                getString(R.string.dk_perm_utils_permissions_location_text2_android11)
Passer par DKResource.convertToString()

2020-08-27 12:38 UTC, Steven-DriveQuant commented on PermissionsUtilsUI/src/main/java/com/drivequant/drivekit/permissionsutils/permissions/activity/LocationPermissionActivity.kt
> +            text_view_location_permission_text2.text = getString(stringResId)
Passer par DKResource.convertToString()

2020-08-27 12:38 UTC, Steven-DriveQuant commented on PermissionsUtilsUI/src/main/java/com/drivequant/drivekit/permissionsutils/permissions/activity/LocationPermissionActivity.kt
> +                        getString(R.string.dk_perm_utils_permissions_text_button_location_settings)
Passer par DKResource.convertToString()

2020-08-27 12:38 UTC, Steven-DriveQuant commented on PermissionsUtilsUI/src/main/java/com/drivequant/drivekit/permissionsutils/permissions/activity/LocationPermissionActivity.kt
> +                        button_request_location_permission.text = getString(R.string.dk_perm_utils_permissions_text_button_location_settings)
Passer par DKResource.convertToString()

2020-08-27 12:38 UTC, Steven-DriveQuant commented on PermissionsUtilsUI/src/main/java/com/drivequant/drivekit/permissionsutils/diagnosis/activity/AppDiagnosisActivity.kt
> +                    intent.putExtra(Intent.EXTRA_TIME, mailBody)
@mohamed-garci Il y-a-til une raison particulière de passer le mailBody dans `EXTRA_TIME` ?

2020-08-28 14:38 UTC, mohamed-garci commented on PermissionsUtilsUI/src/main/java/com/drivequant/drivekit/permissionsutils/permissions/activity/LocationPermissionActivity.kt
> +            text_view_location_permission_text2.text = getString(stringResId)
Done.

2020-08-28 14:38 UTC, mohamed-garci commented on PermissionsUtilsUI/src/main/java/com/drivequant/drivekit/permissionsutils/permissions/activity/LocationPermissionActivity.kt
> +                getString(R.string.dk_perm_utils_permissions_location_text2_android11)
Done.

2020-08-28 14:38 UTC, mohamed-garci commented on PermissionsUtilsUI/src/main/java/com/drivequant/drivekit/permissionsutils/permissions/activity/LocationPermissionActivity.kt
> +                getString(R.string.dk_perm_utils_permissions_location_text1_android11)
Done.

2020-08-28 14:39 UTC, mohamed-garci commented on PermissionsUtilsUI/src/main/java/com/drivequant/drivekit/permissionsutils/permissions/activity/LocationPermissionActivity.kt
> +                        getString(R.string.dk_perm_utils_permissions_text_button_location_settings)
Done.

2020-08-28 14:39 UTC, mohamed-garci commented on PermissionsUtilsUI/src/main/java/com/drivequant/drivekit/permissionsutils/permissions/activity/LocationPermissionActivity.kt
> +                        button_request_location_permission.text = getString(R.string.dk_perm_utils_permissions_text_button_location_settings)
Done.

2020-08-28 14:39 UTC, mohamed-garci commented on PermissionsUtilsUI/src/main/java/com/drivequant/drivekit/permissionsutils/diagnosis/activity/AppDiagnosisActivity.kt
> +                    intent.putExtra(Intent.EXTRA_TIME, mailBody)
C'était une faute de frappe. tout est bon.

2020-09-11 13:38 UTC, Steven-DriveQuant commented on app/src/main/AndroidManifest.xml
>      <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
@mohamed-garci On peut aussi supprimer la permission ici car elle est déjà présente dans PermissionsUtils UI

2020-09-14 13:14 UTC, mohamed-garci commented on app/src/main/AndroidManifest.xml
>      <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
@Steven-DriveQuant Done.

2020-09-14 15:22 UTC, merged