Feature/filter component
DriveQuantPublic/drivekit-ui-android pull request #47
Opened 2020-09-07 12:14 UTC by mohamed-garci

2020-09-07 14:40 UTC, Steven-DriveQuant commented
@mohamed-garci Sur la synthèse, il y a deux différences entre l'app marque blanche et le dev en cours :

![Capture d’écran 2020-09-07 à 16 33 59](https://user-images.githubusercontent.com/56969493/92398369-b66ffd80-f128-11ea-903a-064308c5fdb5.png)
![Capture d’écran 2020-09-07 à 16 35 50](https://user-images.githubusercontent.com/56969493/92398371-b7089400-f128-11ea-8611-4dec51353f14.png)

- Le séparateur nombre de trajets / distance parcourue n'est pas à la bonne place
- Il faut appliquer le même formatteur de distance

2020-09-07 15:26 UTC, Steven-DriveQuant commented
@mohamed-garci Quand je désactive le filtre véhicule, j'accède bien à la liste des trajets mais quand je quitte l'écran j'ai un crash systématique : 

```
2020-09-07 17:24:47.222 12632-12632/com.example.drivekitdemoapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.drivekitdemoapp, PID: 12632
    java.lang.IndexOutOfBoundsException: Element index -1 must be in range [0..2].
        at kotlin.collections.CollectionsKt__ReversedViewsKt.reverseElementIndex$CollectionsKt__ReversedViewsKt(ReversedViews.kt:30)
        at kotlin.collections.CollectionsKt__ReversedViewsKt.access$reverseElementIndex(ReversedViews.kt:1)
        at kotlin.collections.ReversedList.get(ReversedViews.kt:18)
        at com.drivequant.drivekit.ui.trips.adapter.TripsListAdapter.getChild(TripsListAdapter.kt:70)
        at com.drivequant.drivekit.ui.trips.adapter.TripsListAdapter.getChildView(TripsListAdapter.kt:74)
        at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:451)
        at android.widget.AbsListView.obtainView(AbsListView.java:2497)
```

2020-09-07 15:29 UTC, Steven-DriveQuant commented
@mohamed-garci Lorsqu'il n'y a pas de filtre ni de trajets sur le compte, le placeholder n'est plus le bon : 
![Capture d’écran 2020-09-07 à 17 29 10](https://user-images.githubusercontent.com/56969493/92402373-baebe480-f12f-11ea-8932-b53c93713c97.png)

2020-09-07 15:31 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/fragment/TripsListFragment.kt
> +            context?.getString(R.string.dk_driverdata_no_trips_recorded)
@mohamed-garci Utiliser DKResource

2020-09-07 15:32 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/fragment/TripsListFragment.kt
> +        if ((viewModel.filterItems.size != 2 && viewModel.filterItems[0].itemId == null)) {
@mohamed-garci Déplacer cette logique dans le viewModel afin que cela soit plus explicite

2020-09-07 15:36 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/res/values/driver_data_strings.xml
> +   <string name="dk_driverdata_default_filter_option">All my trips</string>
@mohamed-garci Faire traduire les clefs de texte et les intégrer dans le projet avant de soumettre la PR

2020-09-07 15:39 UTC, Steven-DriveQuant commented on app/src/main/java/com/drivekit/demoapp/DriveKitDemoApplication.kt
> -        DriveKit.setApiKey("Your API key here")
@mohamed-garci Restaurer le code existant

2020-09-08 08:42 UTC, mohamed-garci commented on app/src/main/java/com/drivekit/demoapp/DriveKitDemoApplication.kt
> -        DriveKit.setApiKey("Your API key here")
@Steven-DriveQuant Done.

2020-09-08 08:42 UTC, mohamed-garci commented on DriverDataUI/src/main/res/values/driver_data_strings.xml
> +   <string name="dk_driverdata_default_filter_option">All my trips</string>
@Steven-DriveQuant Done.

2020-09-08 08:42 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/fragment/TripsListFragment.kt
> +            context?.getString(R.string.dk_driverdata_no_trips_recorded)
@Steven-DriveQuant Done.

2020-09-08 08:46 UTC, mohamed-garci commented
@Steven-DriveQuant 

* Le séparateur nombre de trajets / distance parcourue n'est pas à la bonne place =>  **OK**
* Il faut appliquer le même formatteur de distance =>  **(C’est la formatteur dans `DKDataFormatter` => on peut faire un point sur ce sujet si tu veux)**
* Les trajets ne sont plus affichés dans le bon ordre (ascending/descending) => **OK**
* Si je passe l'app en background et que je reviens, on ne conserve pas le véhicule sélectionné => **Fixé**
* Le thread UI est ralenti lorsqu'on sélectionne "Tous mes trajets", voir si on peut corriger cela => **On peut regarder ensemble**
* Quand je désactive le filtre véhicule, j'accède bien à la liste des trajets mais quand je quitte l'écran j'ai un crash systématique  => **Fixé**
* idem quand je suis sur la liste des trajets, que je passe l'app en background et que je la remets au 1er plan  => **Fixé**
* Lorsqu'il n'y a pas de filtre ni de trajets sur le compte, le placeholder n'est plus le bon => **Fixé**

2020-09-08 08:58 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/fragment/TripsListFragment.kt
> +        if ((viewModel.filterItems.size != 2 && viewModel.filterItems[0].itemId == null)) {
@Steven-DriveQuant Done.

2020-09-08 12:01 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/DriverDataUI.kt
> +    internal var shouldDisplayVehicleFilter: Boolean = true
@mohamed-garci Renommer en `enableVehicleFilter` pour essayer de conserver les mêmes noms de variables avec celles déjà existantes

2020-09-08 12:01 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/DriverDataUI.kt
> +        this.shouldDisplayVehicleFilter = shouldDisplayVehicleFilter
@mohamed-garci Idem ici

2020-09-08 12:07 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/extension/TripExtension.kt
> +                    }
Si ce bout de code dans le else est le même que dans le if, le sortir afin de n'écrire qu'une seule fois ce bout de code

2020-09-08 14:18 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/viewmodel/TripsListViewModel.kt
> +    var currentItemPosition = 0
@mohamed-garci Renommer en `currentFilterItemPosition` afin d'éviter toute confusion

2020-09-08 14:20 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/fragment/TripsListFragment.kt
> +            }).toSpannable()
@mohamed-garci Déplacer toute cette logique dans une méthode du ViewModel. Ainsi, cette méthode retournera le SpannableString directement et on pourra laisser dans le fragment uniquement `text_view_trips_synthesis.text = viewModel.getTripSynthesisText()`

2020-09-08 14:43 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/viewmodel/TripsListViewModel.kt
> +    var currentItemPosition = 0
@Steven-DriveQuant Done.

2020-09-08 14:43 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/extension/TripExtension.kt
> +                    }
@Steven-DriveQuant Done.

2020-09-08 14:43 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/fragment/TripsListFragment.kt
> +            }).toSpannable()
@Steven-DriveQuant Done.

2020-09-08 14:44 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/DriverDataUI.kt
> +    internal var shouldDisplayVehicleFilter: Boolean = true
@Steven-DriveQuant Done.

2020-09-11 13:05 UTC, Steven-DriveQuant commented on app/src/main/java/com/drivekit/demoapp/DriveKitDemoApplication.kt
> -        DriveKit.setApiKey("Your API key here")
@mohamed-garci Sauf erreur de ma part le code n'a pas été restauré, il faut laisser le commentaire dans les paramètres car il sera utilisé dans le README du sample app.

2020-09-11 13:07 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/fragment/TripsListFragment.kt
> -    override fun onResume() {
@mohamed-garci Il faut vérifier au préalable s'il y a des impacts lorsque la méthode `onResume()` n'est plus surchargée sur cette vue

2020-09-11 14:57 UTC, mohamed-garci commented on app/src/main/java/com/drivekit/demoapp/DriveKitDemoApplication.kt
> -        DriveKit.setApiKey("Your API key here")
@Steven-DriveQuant la totalité des commentaires ont été restaurés.

2020-09-11 14:59 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/fragment/TripsListFragment.kt
> -    override fun onResume() {
@Steven-DriveQuant ça impacte la resynchro des trajets, si on passe l'app en background puis en foreground. ce qui implique la conservation des trajets triés et la position du filtre.

2020-09-11 15:20 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/fragment/TripsListFragment.kt
> -    override fun onResume() {
@mohamed-garci C'est tout à fait exact. Cependant en supprimant le rafraîchissement des trajets dans le `onResume()` cela introduit une régression lorsqu'on supprime un trajet : quand on revient sur la liste le trajet supprimé apparaît toujours.
Il faut donc trouver un moyen de rafraîchir la liste quand on a supprimé un trajet tout en conservant l'état du filtre

2020-09-11 16:46 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/fragment/TripsListFragment.kt
> -    override fun onResume() {
@Steven-DriveQuant  Done.

2020-09-11 16:51 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/fragment/TripsListFragment.kt
> -    override fun onResume() {
@Steven-DriveQuant C'est corrigé, J'ai conservé la même mécanisme qu'on a déjà sur l'app en marque blanche.

2020-09-15 08:12 UTC, Steven-DriveQuant requested changes

2020-09-15 08:12 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/viewmodel/TripsListViewModel.kt
> +        tripsByDate = sortTrips(trips, false)
@mohamed-garci Dans la méthode `sortTrips` le deuxième paramètre est passé en dur. Il faudrait peut-être passer `DriverDataUI.dayTripDescendingOrder` en paramètre depuis le fragment, comme cela a été fait dans `fetchTrips`

2020-09-15 08:12 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/extension/TripExtension.kt
> -                    if (!orderDesc){
@mohamed-garci Est-ce qu'il faut bien inverser la condition ? C'est un bug non lié au développement en cours ?

2020-09-15 08:25 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/extension/TripExtension.kt
> -                    if (!orderDesc){
@Steven-DriveQuant Oui, c'est un bug qui date.

2020-09-15 08:44 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/extension/TripExtension.kt
> -                    if (!orderDesc){
@mohamed-garci Ok dans ce cas il faudra le mentionner dans le changelog

2020-09-15 08:52 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/viewmodel/TripsListViewModel.kt
> +        tripsByDate = sortTrips(trips, false)
@Steven-DriveQuant Done.

2020-09-15 12:38 UTC, Steven-DriveQuant requested changes

2020-09-15 12:38 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/activity/TripsListActivity.kt
> +                    updateTrips()
@mohamed-garci Ici, quand un trajet est supprimé, on appelle `updateTrips()` et dedans cela va appeler `viewModel.fetchTrips()` Cette méthode va faire un appel service car on passe en paramètre via `SynchronizationType.DEFAULT`.
Pour éviter de faire un appel service inutile (la BDD locale est déjà à jour), faire en sorte que `fetchTrips` puisse juste mettre à jour les trajets en appelant les données en BDD locale :
- Remettre le SynchronizationType en second paramètre, avec une valeur par défaut à DEFAULT
- Ajouter aussi ce paramètre dans `updateTrips()`, avec une valeur par défaut à DEFAULT
- Dans la callback `onActivityResult()`, appeler `updateTrips(SynchronizationType.CACHE)`

2020-09-15 12:58 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/trips/activity/TripsListActivity.kt
> +                    updateTrips()
@Steven-DriveQuant Done.

2020-09-23 07:46 UTC, jeremybayle-pro approved these changes

2020-09-24 12:32 UTC, merged