Feature/driver data trip detail customization
DriveQuantPublic/drivekit-ui-android pull request #63
Opened 2020-11-29 18:36 UTC by mohamed-garci

2020-11-30 13:45 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/adapter/TripDetailFragmentPagerAdapter.kt
> +            val hasTrip = tripDetailViewModel.configurableMapItems.size - 1 != position
@mohamed-garci Peux-tu m'expliquer à quoi correspond la condition `tripDetailViewModel.configurableMapItems.size - 1 != position` et pourquoi le boolean s'appelle `hasTrip` ? Je ne suis pas sûr de bien comprendre en haut car on vérifie déjà juste au-dessus que le `tripDetailViewModel` a un trip non null.

2020-11-30 13:50 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/TripDetailFragment.kt
> +                it.getFragment(viewModel.trip!!, viewModel).apply {
@mohamed-garci Est-ce qu'on peut éviter les `!!` ? Nous avons déjà eu des soucis par le passé

2020-11-30 13:54 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/HeaderDay.kt
> +        return text(context, list)
@mohamed-garci Passer directement `return text(context, listOf(trip)`, la MutableList ici n'est pas nécessaire

2020-11-30 14:02 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewholder/TripGoogleMapViewHolder.kt
> +    fun traceRoute(mapItem: DKMapItem?) {
@mohamed-garci Voir si on peut retirer l'optionnel du paramètre

2020-11-30 14:02 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewholder/TripGoogleMapViewHolder.kt
> +    private fun drawMarker(mapItem: DKMapItem?) {
@mohamed-garci Voir ici aussi si on peut retirer l'optionnel du paramètre

2020-11-30 14:15 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/MapItem.kt
> +        when (this) {
@mohamed-garci Ici, il ne faut pas utiliser les `!!`. Par exemple, il y a des trajets anciens qui n'ont pas de Phone Distraction. Ca provoque donc un NPE :

```
2020-11-30 15:11:09.198 15446-15446/com.example.drivekitdemoapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.drivekitdemoapp, PID: 15446
    kotlin.KotlinNullPointerException
        at com.drivequant.drivekit.ui.tripdetail.viewmodel.MapItem.canShowMapItem(MapItem.kt:51)
        at com.drivequant.drivekit.ui.tripdetail.viewmodel.TripDetailViewModel.setTrip(TripDetailViewModel.kt:23)
        at com.drivequant.drivekit.ui.tripdetail.viewmodel.TripDetailViewModel$fetchTripData$1.onResponse(TripDetailViewModel.kt:60)

```

2020-11-30 14:16 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/MapItem.kt
> +        when (this) {
@mohamed-garci Remarque identique concernant l'utilisation des `!!`

2020-11-30 14:29 UTC, Steven-DriveQuant requested changes
@mohamed-garci Pourras-tu regarder mes remarques et faire les modifications si nécessaire ? Si besoin, je suis dispo

2020-11-30 16:32 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewholder/TripGoogleMapViewHolder.kt
> +    private fun drawMarker(mapItem: DKMapItem?) {
@Steven-DriveQuant Ce n'est pas possible, les méthodes `drawMarker` et `traceRoute` ont besoin de savoir si l'item est null. 
Exemple :  l'affichage des marqueurs et le traçage de l'itinéraire d'un trajet non scoré.

2020-11-30 16:40 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewholder/TripGoogleMapViewHolder.kt
> +    private fun drawMarker(mapItem: DKMapItem?) {
@mohamed-garci Ok ça marche merci pour l'explication

2020-11-30 16:40 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/adapter/TripDetailFragmentPagerAdapter.kt
> +            val hasTrip = tripDetailViewModel.configurableMapItems.size - 1 != position
@Steven-DriveQuant `hasTrip` me permet de savoir s'il faut passer l'objet `trip` dans les arguments du fragment pour éviter de faire ça pour les autres (SafetyFragment, EcoDrivingFragment, etc..).

le `customMapItem` vient en dernière position dans la liste `configurableMapItems`.

2020-11-30 17:02 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/HeaderDay.kt
> +        return text(context, list)
@Steven-DriveQuant Passer la liste directement me va.

2020-11-30 17:03 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/MapItem.kt
> +        when (this) {
@Steven-DriveQuant Ça été corrigé. merci pour l'explication.

2020-11-30 17:06 UTC, mohamed-garci commented
> @mohamed-garci Pourras-tu regarder mes remarques et faire les modifications si nécessaire ? Si besoin, je suis dispo

> @Steven-DriveQuant tes remarques ont été prises en compte, j'ai laissé mes réponses aussi.

2020-12-01 07:55 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/adapter/TripDetailFragmentPagerAdapter.kt
> +            val hasTrip = tripDetailViewModel.configurableMapItems.size - 1 != position
@mohamed-garci Ok je commence à comprendre merci pour les explications. Tout d'abord je pense qu'on peut déplacer `val hasTrip = tripDetailViewModel.configurableMapItems.size - 1 != position` juste au-dessus de la ligne `if (!hasTrip)`. 

Pour quel MapItem faut-il envoyer l'objet `trip` dans le Bundle, pour le Synthesis uniquement ?

Ensuite, je ne suis pas sûr que la condition fonctionne car si `position` vaut 1 et `configurableMapItems` vaut 5 alors la condition donne : `val hasTrip = (5-1) != 1` donc `hasTrip` vaut true et donc on passerait l'objet trip pour le deuxième mapItem du PagerAdapter alors qu'il ne le faudrait pas, si je ne me trompe pas

2020-12-01 08:45 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/adapter/TripDetailFragmentPagerAdapter.kt
> +            val hasTrip = tripDetailViewModel.configurableMapItems.size - 1 != position
@Steven-DriveQuant Il faut envoyer l'objet trip dans le Bundle pour le `customFragment` et non pas pour le `SynthesisFragment`.

la condition fonctionne bien : Dans le code =>  `if (!hasTrip)`

2020-12-01 09:39 UTC, Steven-DriveQuant approved these changes

2020-12-01 09:58 UTC, jeremybayle-pro commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/adapter/TripDetailFragmentPagerAdapter.kt
>              }
Ce code n'a pas à être là, il sera ajouté à l'implémentation de l'interface DKMapItem par l'intégrateur qui ajoutera le bundle s'il en a besoin. Il est d'ailleurs dupliqué dans la classe TripDetailFragment ligne 400.

2020-12-01 09:59 UTC, jeremybayle-pro commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/TripDetailFragment.kt
> +                    it
A enlever, voir remarque précédente

2020-12-01 10:06 UTC, jeremybayle-pro commented on app/src/main/java/com/drivekit/demoapp/config/DriveKitConfig.kt
> +        })*/
Il faut nettoyer le code, on ne documente pas cette feature, il ne faut pas donc pas que ça apparaisse dans le code public aussi

2020-12-01 10:06 UTC, jeremybayle-pro commented on app/src/main/java/com/drivekit/demoapp/driverdata/DemoCustomMapItem.kt
> +package com.drivekit.demoapp.driverdata
A supprimer, on ne documente pas cette feature, il ne faut pas donc pas que ça apparaisse dans le code public aussi

2020-12-01 10:38 UTC, mohamed-garci commented on app/src/main/java/com/drivekit/demoapp/driverdata/DemoCustomMapItem.kt
> +package com.drivekit.demoapp.driverdata
@jeremybayle-pro le code a été retiré.

2020-12-01 10:38 UTC, mohamed-garci commented on app/src/main/java/com/drivekit/demoapp/config/DriveKitConfig.kt
> +        })*/
le code a été retiré.

2020-12-01 10:39 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/adapter/TripDetailFragmentPagerAdapter.kt
>              }
le code a été retiré.

2020-12-01 10:42 UTC, jeremybayle-pro approved these changes

2020-12-01 10:45 UTC, merged