Feature/driver distraction v2 UI
DriveQuantPublic/drivekit-ui-android pull request #73
Opened 2021-02-02 16:50 UTC by mohamed-garci

2021-02-10 18:47 UTC, Steven-DriveQuant requested changes
C'est une première passe sur le code, je n'ai pas encore fait le recettage fonctionnel non plus

2021-02-10 18:47 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/MapTraceType.kt
> +enum class MapTraceType {
@mohamed-garci Passer l'enum en `internal`

2021-02-10 18:47 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        return trip?.let { trip ->
@mohamed-garci On pourrait simplifier en faisant `return trip?.calls?.get(position.rem(2))`

2021-02-10 18:47 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        trip?.driverDistraction?.score?.let {
@mohamed-garci 
1/ La méthode s'appelle `getDistractionScore()` dans l'analyse d'impact et ici `getScore()` ? Cela peut d'autant plus provoquer une confusion car nous sommes dans TripDetailViewModel 
2/`0.toDouble()` est à proscrire, cela fait un cast inutile. Ici on pourrait simplifier en faisant return `trip?.driverDistraction?.score ?: 0.0`

2021-02-10 18:47 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        trip?.driverDistraction?.nbUnlock?.let {
@mohamed-garci Ici aussi, simplifier en `return trip?.driverDistraction?.nbUnlock ?: 0`

2021-02-10 18:47 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        var distance = 0
@mohamed-garci On pourrait simplifier de la façon suivante : `val distance = trip?.calls?.map { call -> call.distance}?.sum() ?: 0
`

2021-02-10 18:47 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        trip?.let {
@mohamed-garci Simplifier ici aussi

2021-02-10 18:47 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        trip?.let { trip ->
@mohamed-garci Simplifier ici aussi

2021-02-10 18:47 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/res/layout/dk_distraction_item.xml
> +        tools:ignore="UselessParent">
@mohamed-garci Est-ce qu'on ne pourrait pas enlever le premier `LinearLayout` plutôt que d'ajouter l'annotation `UselessParent` ?

2021-02-11 08:01 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> -            fragment.viewModel =
@Steven-DriveQuant le viewModel est déjà utilisé, c'est juste le type qui a changé.

2021-02-11 08:04 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> -    override fun onSaveInstanceState(outState: Bundle) {
@Steven-DriveQuant J'ai pas mal testé le passage en background -> foreground. c'est OK à priori.

J'ai essayé même de sauvegarder le `viewModel` mais il s'avérait que LiveData n'est pas `Serializable`.

![Screenshot 2021-02-08 at 16 25 17](https://user-images.githubusercontent.com/60616229/107613196-1757b080-6c48-11eb-9396-90dad638bd3f.png)

2021-02-11 08:11 UTC, mohamed-garci commented on CommonUI/src/main/java/com/drivequant/drivekit/common/ui/utils/DKDataFormatter.kt
> +    fun formatDuration(
1. Un point est prévu avec David pour présenter la conception.
2. `maxNbMinute` : c'est la durée maximale en minute au delà de laquelle on affiche pas les secondes.

Puisque les règles de formattage différent d'un écran à un autre, et pour éviter de créer une nouvelle méthode, j'ai adapté la méthode existante.

2021-02-11 08:14 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/MapTraceType.kt
> +enum class MapTraceType {
@Steven-DriveQuant l'enum `MapTraceType` est utilisé dans une interface (`DKTripDetailViewModel`), l'enum elle doit être `public`.

2021-02-11 08:19 UTC, mohamed-garci commented on DriverDataUI/src/main/res/layout/dk_distraction_item.xml
> +        tools:ignore="UselessParent">
@Steven-DriveQuant Le premier `LinearLayout` c'est pour garder la barre verticale et le texte à la même hauteur, et pour que le contenu soit centrer au milieu de la view.

2021-02-11 08:23 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        trip?.let { trip ->
Done.

2021-02-11 08:23 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        trip?.let {
Done.

2021-02-11 08:23 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        var distance = 0
Done.

2021-02-11 08:23 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        trip?.driverDistraction?.nbUnlock?.let {
Done.

2021-02-11 08:24 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        trip?.driverDistraction?.score?.let {
C'est corrigé. merci

2021-02-11 08:24 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        return trip?.let { trip ->
Done.

2021-02-11 08:26 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> +                )
@Steven-DriveQuant Done. (dans le else ce n'est pas un `String`, le type de retour de `buildString()` est un `Spannable`)

2021-02-11 08:26 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> +class DriverDistractionFragment : Fragment(), View.OnClickListener {
Done.

2021-02-11 08:27 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/commons/views/DistractionSelectorItem.kt
> +class DistractionSelectorItem : LinearLayout {
Done.

2021-02-11 08:27 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/commons/views/DistractionItem.kt
> +class DistractionItem : LinearLayout {
Done.

2021-02-11 08:29 UTC, mohamed-garci commented on CommonUI/src/main/java/com/drivequant/drivekit/common/ui/utils/DKDataFormatter.kt
> +    fun formatMeterDistanceInKm(context: Context, distance: Double?, unit: Boolean = true, distanceMax: Int = 100): String {
Pareil comme pour la durée.

distanceMax : la règle aujourd'hui c'est que au de la de 100km, on affiche plus la partie décimale.
Pour la distraction : la règle si la distance > 10km on affiche plus le décimale.

2021-02-11 13:43 UTC, Steven-DriveQuant requested changes
<img width="353" alt="Capture d’écran 2021-02-11 à 11 09 00" src="https://user-images.githubusercontent.com/56969493/107644207-6d901800-6c77-11eb-9bc0-7ed5ceaecfc0.png">

Il faudrait que les nouveaux pin points aient la même taille que ceux qui existent déjà

2021-02-11 13:43 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> -            fragment.viewModel =
Le fichier DriverDistractionViewModel.kt existe encore dans le projet

2021-02-11 13:43 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> -    override fun onSaveInstanceState(outState: Bundle) {
A mon avis quand on repasse dans `onActivityCreated()` et que `tripDetailViewModel` est repassé à `null`, ça crashera. C'est ce que j'ai corrigé dans `UnscoredTripFragment` en début de semaine

2021-02-11 13:43 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/MapTraceType.kt
> +enum class MapTraceType {
@mohamed-garci Ok bien vu !

2021-02-11 13:43 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        }
@mohamed-garci Est-ce que c'est nécessaire de faire une liste d'objets chunkés ? Cela rend la maintenabilité et la lecture un peu difficile, notamment au niveau des lignes `route.latitude[chunkedCallIndex[indexPhoneCall][index]],`

On peut voir ensemble cette partie du code si tu veux

2021-02-11 13:43 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/res/layout/dk_distraction_item.xml
> +        tools:ignore="UselessParent">
@mohamed-garci Ok on va laisser comme ça, je pense qu'on aurait pu utiliser une ConstraintLayout ici pour gérer ces contraintes de placement

2021-02-11 13:52 UTC, Steven-DriveQuant requested changes

2021-02-11 13:52 UTC, Steven-DriveQuant commented on CommonUI/src/main/java/com/drivequant/drivekit/common/ui/utils/DKDataFormatter.kt
> +    fun formatDuration(
@mohamed-garci En soi cela fonctionne, mais cela m'embête car si un jour on veut aussi faire la même chose pour les heures et pour les jours, il faudra ajouter autant de paramètres.
Il faudrait envisager de ceil la durée ou la distance avant d'appeler formatDuration. On a une méthode ceilTripDuration dans l'app marque blanche, à voir si on peut répliquer le fonctionnement. Qu'en penses-tu ?
Vérifier s'il faut ajouter l'annotation `@JvmOverloads` pour assurer la rétrocompatibilité

2021-02-11 13:56 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> +                )
Merci d'avoir fait la modif. Oui dans le if c'est bien une String qui est déjà retournée, dans le else c'était un Spannable donc autant faire le toString() dans le else

2021-02-11 15:33 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> -            fragment.viewModel =
@Steven-DriveQuant J'avais mal compris ta remarque, merci de l'avoir vu ! C'est supprimer.

2021-02-12 16:54 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/viewmodel/TripDetailViewModel.kt
> +        }
@Steven-DriveQuant Ça été simplifié.

2021-02-12 17:01 UTC, mohamed-garci commented on CommonUI/src/main/java/com/drivequant/drivekit/common/ui/utils/DKDataFormatter.kt
> +    fun formatDuration(
@Steven-DriveQuant J'ai rajouté deux méthodes dans `DKDataFormatter`:

- `ceilDuration(durationInSeconds: Double?, ceilValueInSeconds: Int): Double?`

- `ceilDistance(distanceInMeter: Double?, ceilValueInMeter: Int): Double?`

Les deux méthodes permettent de faire un ceil de la valeur avant d'appeler `formatDuration` ou `formatDistance`

Un point de synchro a eu lieu avec l'équipe iOS.

2021-02-12 18:05 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> +                    viewModel.getUnlockDistance(requireContext()).replace(" ","\u00A0")
@Steven-DriveQuant ça été déplacé dans les méthodes de formatage.

2021-02-16 12:21 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> -    override fun onSaveInstanceState(outState: Bundle) {
@Steven-DriveQuant Après reflexion, je me rend compte que `DKTripDetailViewModel` utilisé dans le `DriverDistractionFragment` n'est pas un vraiment un `viewModel` en lui même, mais une interface.

Du coup ce que tu m'as envoyé vendredi peut être appliquer sur les classes `viewModel`.
(https://medium.com/androiddevelopers/viewmodels-persistence-onsaveinstancestate-restoring-ui-state-and-loaders-fc7cc4a6c090)

Si t'as une idée ou une suggestion je suis disponible.

2021-02-16 13:35 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> -    override fun onSaveInstanceState(outState: Bundle) {
@mohamed-garci Oui c'est bien une interface qu'implémente `TripDetailViewModel`. Il faut s'assurer que sur iOS que ce soit également cette interface qui est passée à la carte Distraction.
Je n'ai pas testé depuis mais la proposition dans le lien que je t'avais envoyé devrait pouvoir couvrir le cas

2021-02-16 13:59 UTC, mohamed-garci commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> -    override fun onSaveInstanceState(outState: Bundle) {
@Steven-DriveQuant En fait ce n'est pas trop claire.

2021-02-16 19:57 UTC, DavidBauduin commented on CommonUI/src/main/java/com/drivequant/drivekit/common/ui/utils/DKDataFormatter.kt
> +                        .plus(NON_BREAKING_SPACE)
Sur iOS on n'a pas d'espace entre le nombre de jours et le symbole et entre le nombre d'heures et le symbole (on écrit par exemple "1j 2h" mais pas "1 j 2 h". Je préfère le format iOS et vous ? (Quand la durée est < 1 jour, on a comme vous, par exemple "1h02")

2021-02-17 07:44 UTC, Steven-DriveQuant commented on CommonUI/src/main/java/com/drivequant/drivekit/common/ui/utils/DKDataFormatter.kt
> +                        .plus(NON_BREAKING_SPACE)
Ok avec ça. Du coup, les non-breaking space ne seraient plus nécessaires dans ce cas

2021-02-17 07:49 UTC, Steven-DriveQuant commented on CommonUI/src/main/java/com/drivequant/drivekit/common/ui/utils/DKDataFormatter.kt
> +                        .plus(NON_BREAKING_SPACE)
@David Ok avec ça. Gère tu les espaces insécables dans DKDataFormatter, du coup ?

2021-02-17 08:18 UTC, DavidBauduin commented on CommonUI/src/main/java/com/drivequant/drivekit/common/ui/utils/DKDataFormatter.kt
> +                        .plus(NON_BREAKING_SPACE)
Oui je les ai pris en compte hier.

2021-02-18 17:36 UTC, Steven-DriveQuant approved these changes

2021-02-18 17:39 UTC, merged