WIP : Integrate new SPEEDING score.
DriveQuantPublic/drivekit-ui-android pull request #82
Opened 2021-03-02 09:53 UTC by mohamed-garci

2021-03-05 13:38 UTC, Steven-DriveQuant commented on CommonUI/src/main/java/com/drivequant/drivekit/common/ui/component/GaugeIndicator.kt
> +            SPEEDING -> listOf(0.0, 3.0, 5.0, 7.0, 8.0, 9.0, 9.5, 10.0)
@mohamed-garci Il y a 8 valeurs dans la liste pour le SPEEDING alors qu'il y en a 7 pour les autres. Cela peut provoquer des erreurs dans l'affichage.

2021-03-05 14:45 UTC, Steven-DriveQuant requested changes

2021-03-05 14:45 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> +
Rajouter un else dans le when pour supprimer le warning affiché dans l'IDE

2021-03-05 14:45 UTC, Steven-DriveQuant commented on CommonUI/src/main/java/com/drivequant/drivekit/common/ui/component/GaugeIndicator.kt
> +            SPEEDING -> listOf(0.0, 3.0, 5.0, 7.0, 8.0, 9.0, 9.5, 10.0)
Il y a 8 valeurs dans la liste pour le SPEEDING alors qu'il y en a 7 pour les autres. Cela peut provoquer des erreurs dans l'affichage.

2021-03-05 14:45 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/tripdetail/fragments/DriverDistractionFragment.kt
> +        score_info.setOnClickListener {
Ce code est répété 4 fois (safety, ecodriving, distraction speeding). Ce serait bien d'en faire une View dédiée pour factoriser le code.

2021-03-09 07:33 UTC, mohamed-garci commented on CommonUI/src/main/java/com/drivequant/drivekit/common/ui/component/GaugeIndicator.kt
> +            SPEEDING -> listOf(0.0, 3.0, 5.0, 7.0, 8.0, 9.0, 9.5, 10.0)
@Steven-DriveQuant en fait il fallait pas ajouter la valeur 0, d'ailleurs je me demande pourquoi en SAFETY c'est le cas.
ça été corrigé du coup.

2021-03-09 07:56 UTC, Steven-DriveQuant commented on CommonUI/src/main/java/com/drivequant/drivekit/common/ui/component/GaugeIndicator.kt
> +            SPEEDING -> listOf(0.0, 3.0, 5.0, 7.0, 8.0, 9.0, 9.5, 10.0)
@mohamed-garci Le vecteur des valeurs de la jauge doit avoir une taille de 7. Avec `SPEEDING -> listOf(0.0, 3.0, 5.0, 7.0, 8.0, 9.0, 9.5, 10.0)` le speeding en avait 8 d'où le décalage des couleurs de la jauge remonté par Pauline

2021-03-09 14:42 UTC, Steven-DriveQuant commented on DriverDataUI/src/main/java/com/drivequant/drivekit/ui/extension/GaugeTypeExtension.kt
> +fun GaugeType.getScoreInfoTitle(): String =
Pour ces deux méthodes, il vaut mieux retourrner la valeur de la clé de texte directement, car le nom de la méthode n'indique pas que c'est la clé de texte qui est renvoyée.

2021-03-10 09:35 UTC, merged