Challenge List UI
DriveQuantPublic/drivekit-ui-android pull request #94
Opened 2021-05-03 09:19 UTC by mohamed-garci

2021-05-05 16:18 UTC, Steven-DriveQuant commented
Hello,

Voici des remarques complémentaires :
- Reset le module Challenge et DriverAchievement dans la méthode r`econfigureDriveKit()` de `SettingsActivity.kt`
- On ne peut pas swiper entre la liste des challenges actifs et terminés comme dans l'app marque blanche
- Ce serait bien de rajouter un effet ripple sur les éléments de la liste (ce n'est pas présent sur l'app marque blanche, mais ça indique à l'utilisateur que l'item est cliquable)

2021-05-05 16:34 UTC, Steven-DriveQuant requested changes

2021-05-05 16:34 UTC, Steven-DriveQuant commented on ChallengeUI/src/main/java/com/drivequant/drivekit/challenge/ui/viewmodel/ChallengeListViewModel.kt
> +            for (status in statusList) {
Voir si on peut remplacer ce for imbriqué par `if (statusList.contains(challengeData.status)){ ... }`

2021-05-05 16:34 UTC, Steven-DriveQuant commented on ChallengeUI/src/main/java/com/drivequant/drivekit/challenge/ui/viewmodel/ChallengeStatusData.kt
> +class ChallengeStatusData(
S'assurer si l'on peut passer cette classe (et les autres de la PR, comme ChallengeListAdapter ou ChallengeViewHolder) en internal

2021-05-05 16:34 UTC, Steven-DriveQuant commented on ChallengeUI/src/main/res/layout/dk_challenge_empty_view.xml
> +        android:contentDescription="TODO" />
Retirer le TODO

2021-05-06 07:09 UTC, mohamed-garci commented on ChallengeUI/src/main/java/com/drivequant/drivekit/challenge/ui/fragment/ChallengeListFragment.kt
> +                "dk_tag_challenge-list"
Ça été rajouté. merci de l'avoir vu !

2021-05-06 07:17 UTC, mohamed-garci commented
> Hello,
> 
> Voici des remarques complémentaires :
> 
> * Reset le module Challenge et DriverAchievement dans la méthode r`econfigureDriveKit()` de `SettingsActivity.kt`
> * On ne peut pas swiper entre la liste des challenges actifs et terminés comme dans l'app marque blanche
> * Ce serait bien de rajouter un effet ripple sur les éléments de la liste (ce n'est pas présent sur l'app marque blanche, mais ça indique à l'utilisateur que l'item est cliquable)

Hello, 

-> Reset des modules => OK
-> Ripple effect => OK

2021-05-06 16:57 UTC, Steven-DriveQuant approved these changes

2021-05-07 08:59 UTC, merged